name: Build and deploy Docker image

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://howto.acdh.oeaw.ac.at
            NEXT_PUBLIC_REDMINE_ID=6848
            NEXT_PUBLIC_MATOMO_BASE_URL=https://matomo.acdh.oeaw.ac.at
            NEXT_PUBLIC_MATOMO_ID=199
            NEXT_PUBLIC_LOCAL_CMS=disabled
            NEXT_PUBLIC_GIT_REPO=${{ github.repository }}
            NEXT_PUBLIC_GIT_BRANCH=main
            NEXT_PUBLIC_TYPESENSE_HOST=typesense.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_TYPESENSE_PORT=443
            NEXT_PUBLIC_TYPESENSE_PROTOCOL=https
            NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY=${{ secrets.NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY }}
          secrets: |
            "GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "TYPESENSE_ADMIN_API_KEY=${{ secrets.TYPESENSE_ADMIN_API_KEY }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster
        env:
          RANCHER_PROJECT_ID: c-zdbh8:p-6vb45
          RANCHER_DEPLOYMENT: howto:howto
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.RANCHER_API_TOKEN }}" \
            'https://rancher.acdh-dev.oeaw.ac.at/v3/project/${{env.RANCHER_PROJECT_ID}}/workloads/deployment:${{env.RANCHER_DEPLOYMENT}}?action=redeploy'
